<?php

use App\Enums\AuditAction;
use App\Enums\AuditCategory;
use App\Enums\AuditDomain;
use App\Enums\AuditOutcome;
use App\Enums\AuditSeverity;

return [
    'log_name' => 'audit',

    /*
    | Taxonomy is defined once on the backend. API presenters can expose these
    | values to clients without requiring a second hard-coded frontend list.
    */
    'taxonomy' => [
        'actions' => AuditAction::class,
        'categories' => AuditCategory::class,
        'domains' => AuditDomain::class,
        'outcomes' => AuditOutcome::class,
        'severities' => AuditSeverity::class,

        'category_actions' => [
            AuditCategory::Security->value => [
                AuditAction::Created->value,
                AuditAction::Updated->value,
                AuditAction::Deleted->value,
                AuditAction::ProfileChanged->value,
                AuditAction::LoginSucceeded->value,
                AuditAction::LoginFailed->value,
                AuditAction::AuthenticationFailed->value,
                AuditAction::Logout->value,
                AuditAction::PasswordChanged->value,
                AuditAction::PasswordReset->value,
                AuditAction::RecoveryEmailChanged->value,
                AuditAction::RecoveryEmailVerified->value,
                AuditAction::RateLimitExceeded->value,
                AuditAction::AuthorizationDenied->value,
                AuditAction::AuditLogViewed->value,
                AuditAction::AccountBlocked->value,
                AuditAction::AccountUnblocked->value,
                AuditAction::IpBlocked->value,
                AuditAction::IpUnblocked->value,
            ],
            AuditCategory::Clinical->value => [
                AuditAction::Created->value,
                AuditAction::Updated->value,
                AuditAction::Deleted->value,
                AuditAction::Viewed->value,
                AuditAction::Downloaded->value,
                AuditAction::Exported->value,
                AuditAction::Uploaded->value,
                AuditAction::Generated->value,
                AuditAction::Approved->value,
            ],
            AuditCategory::Operations->value => [
                AuditAction::Created->value,
                AuditAction::Updated->value,
                AuditAction::Deleted->value,
                AuditAction::Viewed->value,
                AuditAction::Downloaded->value,
                AuditAction::Exported->value,
                AuditAction::Approved->value,
                AuditAction::Received->value,
                AuditAction::Reversed->value,
                AuditAction::Archived->value,
                AuditAction::Adjusted->value,
                AuditAction::Uploaded->value,
                AuditAction::Generated->value,
                AuditAction::Completed->value,
                AuditAction::PriceCorrected->value,
                AuditAction::ProfileChanged->value,
                AuditAction::SettingsChanged->value,
            ],
        ],
    ],

    /* Retention values are defaults pending privacy-owner approval. */
    'retention' => [
        AuditCategory::Security->value => ['days' => 365, 'legal_hold' => false],
        AuditCategory::Clinical->value => ['days' => 2190, 'legal_hold' => false],
        AuditCategory::Operations->value => ['days' => 1095, 'legal_hold' => false],
        'legacy' => ['days' => 90, 'legal_hold' => false],
    ],

    'deduplication' => [
        'chart_view_seconds' => 15 * 60,
        'security_failure_seconds' => 5 * 60,
    ],

    'features' => [
        'export' => env('AUDIT_EXPORT_ENABLED', false),
        'ip_blocking' => env('AUDIT_SECURITY_BLOCKS_ENABLED', false),
    ],
    /* Every unsafe route must be reviewed; there is no fallback classifier. */
    'route_coverage' => [
        'POST _boost/browser-logs' => [
            'classification' => 'intentionally_not_audited',
            'source' => 'Laravel\\Boost\\BoostServiceProvider@registerRoutes',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Laravel Boost development telemetry is outside the application API.',
        ],
        'PUT api/admin/ai-usage-limits' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\Admin\\AiUsageLimitController@update',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful PUT api/admin/ai-usage-limits emits one sanitized explicit event; rejected commands emit none.',
        ],
        'POST api/admin/announcements' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\Admin\\AnnouncementController@store',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful POST api/admin/announcements emits one sanitized explicit event; rejected commands emit none.',
        ],
        'PATCH api/admin/announcements/{announcement}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\Admin\\AnnouncementController@update',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful PATCH api/admin/announcements/{announcement} emits one sanitized explicit event; rejected commands emit none.',
        ],
        'DELETE api/admin/announcements/{announcement}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\Admin\\AnnouncementController@destroy',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful DELETE api/admin/announcements/{announcement} emits one sanitized explicit event; rejected commands emit none.',
        ],
        'PUT api/admin/food-service-settings' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\FoodServiceSettingController@update',
            'owner_task' => 7,
            'implementation_state' => 'planned',
            'reason' => 'This administrative setting command needs an explicit actor, safe field list, and outcome event.',
        ],
        'POST api/admin/report-branding' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\ReportBrandingController@update',
            'owner_task' => 8,
            'implementation_state' => 'planned',
            'reason' => 'This report-configuration command needs an explicit safe allow-listed change event; images and arbitrary payloads stay excluded.',
        ],
        'DELETE api/admin/reports/{report}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\ReportController@destroy',
            'owner_task' => 8,
            'implementation_state' => 'planned',
            'reason' => 'This report lifecycle command needs an explicit outcome event without report snapshots, filters, or file contents.',
        ],
        'POST api/admin/reports/{type}/archive' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\ReportController@archive',
            'owner_task' => 8,
            'implementation_state' => 'planned',
            'reason' => 'This report lifecycle command needs an explicit outcome event without report snapshots, filters, or file contents.',
        ],
        'POST api/admin/users' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\Admin\\UserController@store',
            'owner_task' => 5,
            'implementation_state' => 'implemented',
            'reason' => 'This administrative account command needs an explicit actor, target, and outcome event without credential values.',
        ],
        'PUT api/admin/users/{user}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\Admin\\UserController@update',
            'owner_task' => 5,
            'implementation_state' => 'implemented',
            'reason' => 'This administrative account command needs an explicit actor, target, and outcome event without credential values.',
        ],
        'PATCH api/admin/users/{user}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\Admin\\UserController@update',
            'owner_task' => 5,
            'implementation_state' => 'implemented',
            'reason' => 'This administrative account command needs an explicit actor, target, and outcome event without credential values.',
        ],
        'DELETE api/admin/users/{user}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\Admin\\UserController@destroy',
            'owner_task' => 5,
            'implementation_state' => 'implemented',
            'reason' => 'This administrative account command needs an explicit actor, target, and outcome event without credential values.',
        ],
        'POST api/admin/users/{user}/reset-password' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\Admin\\UserController@resetPassword',
            'owner_task' => 5,
            'implementation_state' => 'implemented',
            'reason' => 'This administrative account command needs an explicit actor, target, and outcome event without credential values.',
        ],
        'POST api/auth/forgot-password' => [
            'classification' => 'intentionally_not_audited',
            'source' => 'App\\Http\\Controllers\\Auth\\PasswordResetController@sendResetLink',
            'owner_task' => 5,
            'implementation_state' => 'implemented',
            'reason' => 'The generic reset-link response intentionally emits no account event, avoiding an audit-based account-enumeration signal; actual 429 responses are audited by the named limiter.',
        ],
        'POST api/auth/login' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\Auth\\AuthController@login',
            'owner_task' => 5,
            'implementation_state' => 'implemented',
            'reason' => 'This authentication or account-security command needs an explicit outcome event; credentials, tokens, and codes stay excluded.',
        ],
        'POST api/auth/logout' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\Auth\\AuthController@logout',
            'owner_task' => 5,
            'implementation_state' => 'implemented',
            'reason' => 'This authentication or account-security command needs an explicit outcome event; credentials, tokens, and codes stay excluded.',
        ],
        'POST api/auth/password' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\Auth\\AuthController@updatePassword',
            'owner_task' => 5,
            'implementation_state' => 'implemented',
            'reason' => 'This authentication or account-security command needs an explicit outcome event; credentials, tokens, and codes stay excluded.',
        ],
        'PATCH api/auth/profile' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\Auth\\AuthController@updateProfile',
            'owner_task' => 5,
            'implementation_state' => 'implemented',
            'reason' => 'This authentication or account-security command needs an explicit outcome event; credentials, tokens, and codes stay excluded.',
        ],
        'PATCH api/auth/recovery-email' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\Auth\\RecoveryEmailController@update',
            'owner_task' => 5,
            'implementation_state' => 'implemented',
            'reason' => 'This authentication or account-security command needs an explicit outcome event; credentials, tokens, and codes stay excluded.',
        ],
        'POST api/auth/recovery-email/verify' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\Auth\\RecoveryEmailController@verify',
            'owner_task' => 5,
            'implementation_state' => 'implemented',
            'reason' => 'This authentication or account-security command needs an explicit outcome event; credentials, tokens, and codes stay excluded.',
        ],
        'POST api/auth/reset-password' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\Auth\\PasswordResetController@reset',
            'owner_task' => 5,
            'implementation_state' => 'implemented',
            'reason' => 'This authentication or account-security command needs an explicit outcome event; credentials, tokens, and codes stay excluded.',
        ],
        'POST api/fss/budgets' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\BudgetController@store',
            'owner_task' => 7,
            'implementation_state' => 'planned',
            'reason' => 'This budget command needs an explicit business event so adjustment intent and outcome are preserved safely.',
        ],
        'POST api/fss/budgets/adjust' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\BudgetController@manualAdjust',
            'owner_task' => 7,
            'implementation_state' => 'planned',
            'reason' => 'This budget command needs an explicit business event so adjustment intent and outcome are preserved safely.',
        ],
        'POST api/fss/diet-list-counts' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\DietListCountController@store',
            'owner_task' => 7,
            'implementation_state' => 'planned',
            'reason' => 'Diet-list count persistence for POST api/fss/diet-list-counts is covered by its model lifecycle event without duplicate request logging.',
        ],
        'POST api/fss/food-service-recipes' => [
            'classification' => 'model_event',
            'source' => 'App\\Models\\FoodServiceRecipe::AuditsChanges',
            'owner_task' => 7,
            'implementation_state' => 'planned',
            'reason' => 'Food-service recipe persistence for POST api/fss/food-service-recipes is covered by its model lifecycle event.',
        ],
        'PUT|PATCH api/fss/food-service-recipes/{food_service_recipe}' => [
            'classification' => 'model_event',
            'source' => 'App\\Models\\FoodServiceRecipe::AuditsChanges',
            'owner_task' => 7,
            'implementation_state' => 'planned',
            'reason' => 'Food-service recipe persistence for PUT|PATCH api/fss/food-service-recipes/{food_service_recipe} is covered by its model lifecycle event.',
        ],
        'DELETE api/fss/food-service-recipes/{food_service_recipe}' => [
            'classification' => 'model_event',
            'source' => 'App\\Models\\FoodServiceRecipe::AuditsChanges',
            'owner_task' => 7,
            'implementation_state' => 'planned',
            'reason' => 'Food-service recipe persistence for DELETE api/fss/food-service-recipes/{food_service_recipe} is covered by its model lifecycle event.',
        ],
        'PUT api/fss/food-service-settings' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\FoodServiceSettingController@update',
            'owner_task' => 7,
            'implementation_state' => 'planned',
            'reason' => 'This administrative setting command needs an explicit actor, safe field list, and outcome event.',
        ],
        'POST api/fss/fs-items' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\FsItemController@store',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful POST api/fss/fs-items emits one sanitized explicit event; rejected commands emit none.',
        ],
        'PATCH api/fss/fs-items/{fsItem}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\FsItemController@update',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful PATCH api/fss/fs-items/{fsItem} emits one sanitized explicit event; rejected commands emit none.',
        ],
        'DELETE api/fss/fs-items/{fsItem}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\FsItemController@destroy',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful DELETE api/fss/fs-items/{fsItem} emits one sanitized explicit event; rejected commands emit none.',
        ],
        'PATCH api/fss/fs-items/{fsItem}/vendor-lock' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\FsItemController@toggleDefaultSupplierLock',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful PATCH api/fss/fs-items/{fsItem}/vendor-lock emits one sanitized explicit event; rejected commands emit none.',
        ],
        'POST api/fss/meal-prep-logs/{mealPrepLog}/reverse' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\MealPrepLogController@reverse',
            'owner_task' => 7,
            'implementation_state' => 'planned',
            'reason' => 'This meal-service lifecycle command needs an explicit domain event describing its business outcome.',
        ],
        'POST api/fss/menu-cycle-templates' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\MenuCycleTemplateController@store',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful POST api/fss/menu-cycle-templates emits one sanitized explicit event; rejected commands emit none.',
        ],
        'PUT|PATCH api/fss/menu-cycle-templates/{menu_cycle_template}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\MenuCycleTemplateController@update',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful PUT|PATCH api/fss/menu-cycle-templates/{menu_cycle_template} emits one sanitized explicit event; rejected commands emit none.',
        ],
        'DELETE api/fss/menu-cycle-templates/{menu_cycle_template}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\MenuCycleTemplateController@destroy',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful DELETE api/fss/menu-cycle-templates/{menu_cycle_template} emits one sanitized explicit event; rejected commands emit none.',
        ],
        'POST api/fss/menu-cycle-templates/{menu_cycle_template}/instantiate' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\MenuCycleTemplateController@instantiate',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful POST api/fss/menu-cycle-templates/{menu_cycle_template}/instantiate emits one sanitized explicit event; rejected commands emit none.',
        ],
        'POST api/fss/menu-cycles' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\MenuCycleController@store',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful POST api/fss/menu-cycles emits one sanitized explicit event; rejected commands emit none.',
        ],
        'POST api/fss/menu-cycles/{menuCycle}/complete-day' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\MealPrepLogController@complete',
            'owner_task' => 7,
            'implementation_state' => 'planned',
            'reason' => 'Successful POST api/fss/menu-cycles/{menuCycle}/complete-day emits one sanitized explicit event; rejected commands emit none.',
        ],
        'PATCH api/fss/menu-cycles/{menuCycle}/served-population' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\MealPrepLogController@setServed',
            'owner_task' => 7,
            'implementation_state' => 'planned',
            'reason' => 'Successful PATCH api/fss/menu-cycles/{menuCycle}/served-population emits one sanitized explicit event; rejected commands emit none.',
        ],
        'PUT|PATCH api/fss/menu-cycles/{menu_cycle}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\MenuCycleController@update',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful PUT|PATCH api/fss/menu-cycles/{menu_cycle} emits one sanitized explicit event; rejected commands emit none.',
        ],
        'DELETE api/fss/menu-cycles/{menu_cycle}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\MenuCycleController@destroy',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful DELETE api/fss/menu-cycles/{menu_cycle} emits one sanitized explicit event; rejected commands emit none.',
        ],
        'PATCH api/fss/menu-cycles/{menu_cycle}/activate' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\MenuCycleController@activate',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful PATCH api/fss/menu-cycles/{menu_cycle}/activate emits one sanitized explicit event; rejected commands emit none.',
        ],
        'POST api/fss/menu-cycles/{menu_cycle}/save-template' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\MenuCycleTemplateController@fromCycle',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful POST api/fss/menu-cycles/{menu_cycle}/save-template emits one sanitized explicit event; rejected commands emit none.',
        ],
        'DELETE api/fss/purchase-order-attachments/{attachment}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\PurchaseOrderController@destroyAttachment',
            'owner_task' => 7,
            'implementation_state' => 'planned',
            'reason' => 'This procurement command needs an explicit purchase-order-root event without attachment or receipt contents.',
        ],
        'PATCH api/fss/purchase-order-vendor-groups/{vendorGroup}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\PurchaseOrderController@updateVendorGroup',
            'owner_task' => 7,
            'implementation_state' => 'planned',
            'reason' => 'This procurement command needs an explicit purchase-order-root event without attachment or receipt contents.',
        ],
        'POST api/fss/purchase-order-vendor-groups/{vendorGroup}/attachments' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\PurchaseOrderController@uploadVendorGroupAttachment',
            'owner_task' => 7,
            'implementation_state' => 'planned',
            'reason' => 'This procurement command needs an explicit purchase-order-root event without attachment or receipt contents.',
        ],
        'PUT|PATCH api/fss/purchase-orders/{purchase_order}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\PurchaseOrderController@update',
            'owner_task' => 7,
            'implementation_state' => 'planned',
            'reason' => 'This procurement command needs an explicit purchase-order-root event without attachment or receipt contents.',
        ],
        'DELETE api/fss/purchase-orders/{purchase_order}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\PurchaseOrderController@destroy',
            'owner_task' => 7,
            'implementation_state' => 'planned',
            'reason' => 'This procurement command needs an explicit purchase-order-root event without attachment or receipt contents.',
        ],
        'POST api/fss/purchase-orders/{purchase_order}/attachments' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\PurchaseOrderController@uploadAttachment',
            'owner_task' => 7,
            'implementation_state' => 'planned',
            'reason' => 'This procurement command needs an explicit purchase-order-root event without attachment or receipt contents.',
        ],
        'POST api/fss/report-branding' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\ReportBrandingController@update',
            'owner_task' => 8,
            'implementation_state' => 'planned',
            'reason' => 'This report-configuration command needs an explicit safe allow-listed change event; images and arbitrary payloads stay excluded.',
        ],
        'PATCH api/fss/report-templates/{reportTemplate}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\ReportTemplateController@update',
            'owner_task' => 8,
            'implementation_state' => 'planned',
            'reason' => 'This report-configuration command needs an explicit safe allow-listed change event; images and arbitrary payloads stay excluded.',
        ],
        'POST api/fss/reports' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\ReportController@store',
            'owner_task' => 8,
            'implementation_state' => 'planned',
            'reason' => 'This report lifecycle command needs an explicit outcome event without report snapshots, filters, or file contents.',
        ],
        'POST api/fss/reports/generate-all' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\ReportController@generateAll',
            'owner_task' => 8,
            'implementation_state' => 'planned',
            'reason' => 'This report lifecycle command needs an explicit outcome event without report snapshots, filters, or file contents.',
        ],
        'DELETE api/fss/reports/{report}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\ReportController@destroy',
            'owner_task' => 8,
            'implementation_state' => 'planned',
            'reason' => 'This report lifecycle command needs an explicit outcome event without report snapshots, filters, or file contents.',
        ],
        'POST api/fss/reports/{type}/archive' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\ReportController@archive',
            'owner_task' => 8,
            'implementation_state' => 'planned',
            'reason' => 'This report lifecycle command needs an explicit outcome event without report snapshots, filters, or file contents.',
        ],
        'PATCH api/fss/shopping-list-items/{shopping_list_item}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\ShoppingListController@updateItem',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful PATCH api/fss/shopping-list-items/{shopping_list_item} emits one sanitized explicit event; rejected commands emit none.',
        ],
        'DELETE api/fss/shopping-list-items/{shopping_list_item}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\ShoppingListController@destroyItem',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful DELETE api/fss/shopping-list-items/{shopping_list_item} emits one sanitized explicit event; rejected commands emit none.',
        ],
        'POST api/fss/shopping-lists' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\ShoppingListController@store',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful POST api/fss/shopping-lists emits one sanitized explicit event; rejected commands emit none.',
        ],
        'POST api/fss/shopping-lists/generate' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\ShoppingListController@generate',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful POST api/fss/shopping-lists/generate emits one sanitized explicit event; rejected commands emit none.',
        ],
        'PUT|PATCH api/fss/shopping-lists/{shopping_list}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\ShoppingListController@update',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful PUT|PATCH api/fss/shopping-lists/{shopping_list} emits one sanitized explicit event; rejected commands emit none.',
        ],
        'DELETE api/fss/shopping-lists/{shopping_list}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\ShoppingListController@destroy',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful DELETE api/fss/shopping-lists/{shopping_list} emits one sanitized explicit event; rejected commands emit none.',
        ],
        'POST api/fss/shopping-lists/{shopping_list}/approve' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\PurchaseOrderController@approve',
            'owner_task' => 7,
            'implementation_state' => 'planned',
            'reason' => 'Successful POST api/fss/shopping-lists/{shopping_list}/approve emits one sanitized explicit event; rejected commands emit none.',
        ],
        'POST api/fss/shopping-lists/{shopping_list}/items' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\ShoppingListController@storeItem',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful POST api/fss/shopping-lists/{shopping_list}/items emits one sanitized explicit event; rejected commands emit none.',
        ],
        'POST api/fss/suppliers' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\SupplierController@store',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful POST api/fss/suppliers emits one sanitized explicit event; rejected commands emit none.',
        ],
        'PUT|PATCH api/fss/suppliers/{supplier}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\SupplierController@update',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful PUT|PATCH api/fss/suppliers/{supplier} emits one sanitized explicit event; rejected commands emit none.',
        ],
        'DELETE api/fss/suppliers/{supplier}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\FSS\\SupplierController@destroy',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful DELETE api/fss/suppliers/{supplier} emits one sanitized explicit event; rejected commands emit none.',
        ],
        'PATCH api/notifications/read-all' => [
            'classification' => 'intentionally_not_audited',
            'source' => 'App\\Http\\Controllers\\RND\\NotificationController@readAll',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Notification read state is routine UI housekeeping.',
        ],
        'PATCH api/notifications/{notification}/read' => [
            'classification' => 'intentionally_not_audited',
            'source' => 'App\\Http\\Controllers\\RND\\NotificationController@read',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Notification read state is routine UI housekeeping.',
        ],
        'POST api/rnd/announcements' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\RND\\AnnouncementController@store',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful POST api/rnd/announcements emits one sanitized explicit event; rejected commands emit none.',
        ],
        'PATCH api/rnd/announcements/{announcement}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\RND\\AnnouncementController@update',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful PATCH api/rnd/announcements/{announcement} emits one sanitized explicit event; rejected commands emit none.',
        ],
        'DELETE api/rnd/announcements/{announcement}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\RND\\AnnouncementController@destroy',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful DELETE api/rnd/announcements/{announcement} emits one sanitized explicit event; rejected commands emit none.',
        ],
        'POST api/rnd/calendar-events' => [
            'classification' => 'intentionally_not_audited',
            'source' => 'App\\Http\\Controllers\\RND\\CalendarEventController@store',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Calendar reminders are low-risk personal workflow state.',
        ],
        'POST api/rnd/food-items' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\RND\\FoodItemController@store',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful POST api/rnd/food-items emits one sanitized explicit event; rejected commands emit none.',
        ],
        'PUT|PATCH api/rnd/food-items/{food_item}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\RND\\FoodItemController@update',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful PUT|PATCH api/rnd/food-items/{food_item} emits one sanitized explicit event; rejected commands emit none.',
        ],
        'DELETE api/rnd/food-items/{food_item}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\RND\\FoodItemController@destroy',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful DELETE api/rnd/food-items/{food_item} emits one sanitized explicit event; rejected commands emit none.',
        ],
        'DELETE api/rnd/meal-plan-templates/{template}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\RND\\MealPlanController@destroyTemplate',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'Meal-plan template persistence for DELETE api/rnd/meal-plan-templates/{template} is covered by its model lifecycle event.',
        ],
        'DELETE api/rnd/ncp-records/{ncpRecord}' => [
            'classification' => 'model_event',
            'source' => 'App\\Models\\NcpRecord::AuditsChanges',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'NCP record persistence for DELETE api/rnd/ncp-records/{ncpRecord} is covered by its redacted clinical model event.',
        ],
        'POST api/rnd/ncp-records/{ncpRecord}/assessment' => [
            'classification' => 'model_event',
            'source' => 'App\\Models\\Assessment::AuditsChanges',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'Assessment persistence for POST api/rnd/ncp-records/{ncpRecord}/assessment is covered by its redacted clinical model event.',
        ],
        'PATCH api/rnd/ncp-records/{ncpRecord}/assessment' => [
            'classification' => 'model_event',
            'source' => 'App\\Models\\Assessment::AuditsChanges',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'Assessment persistence for PATCH api/rnd/ncp-records/{ncpRecord}/assessment is covered by its redacted clinical model event.',
        ],
        'POST api/rnd/ncp-records/{ncpRecord}/attachments' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\RND\\AssessmentController@uploadAttachment',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'This sensitive attachment command needs an explicit root-context event without paths, file contents, or OCR data.',
        ],
        'POST api/rnd/ncp-records/{ncpRecord}/diagnoses' => [
            'classification' => 'model_event',
            'source' => 'App\\Models\\Diagnosis::AuditsChanges',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'Diagnosis persistence for POST api/rnd/ncp-records/{ncpRecord}/diagnoses is covered by its redacted clinical model event.',
        ],
        'POST api/rnd/ncp-records/{ncpRecord}/diagnoses/ai-approve' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\RND\\AiDiagnosisController@aiApprove',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'Saving an AI-assisted approval needs an explicit clinical outcome event without prompts or model output.',
        ],
        'POST api/rnd/ncp-records/{ncpRecord}/diagnoses/ai-suggest' => [
            'classification' => 'intentionally_not_audited',
            'source' => 'App\\Http\\Controllers\\RND\\AiDiagnosisController@aiSuggest',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Unsaved AI suggestions must not persist prompts or outputs.',
        ],
        'PATCH api/rnd/ncp-records/{ncpRecord}/diagnoses/{diagnosis}' => [
            'classification' => 'model_event',
            'source' => 'App\\Models\\Diagnosis::AuditsChanges',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'Diagnosis persistence for PATCH api/rnd/ncp-records/{ncpRecord}/diagnoses/{diagnosis} is covered by its redacted clinical model event.',
        ],
        'DELETE api/rnd/ncp-records/{ncpRecord}/diagnoses/{diagnosis}' => [
            'classification' => 'model_event',
            'source' => 'App\\Models\\Diagnosis::AuditsChanges',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'Diagnosis persistence for DELETE api/rnd/ncp-records/{ncpRecord}/diagnoses/{diagnosis} is covered by its redacted clinical model event.',
        ],
        'POST api/rnd/ncp-records/{ncpRecord}/intervention' => [
            'classification' => 'model_event',
            'source' => 'App\\Models\\Intervention::AuditsChanges',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'Intervention persistence for POST api/rnd/ncp-records/{ncpRecord}/intervention is covered by its redacted clinical model event.',
        ],
        'PATCH api/rnd/ncp-records/{ncpRecord}/intervention' => [
            'classification' => 'model_event',
            'source' => 'App\\Models\\Intervention::AuditsChanges',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'Intervention persistence for PATCH api/rnd/ncp-records/{ncpRecord}/intervention is covered by its redacted clinical model event.',
        ],
        'POST api/rnd/ncp-records/{ncpRecord}/intervention/autofill' => [
            'classification' => 'intentionally_not_audited',
            'source' => 'App\\Http\\Controllers\\RND\\InterventionController@autofill',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Unsaved AI output must not persist prompts or outputs.',
        ],
        'POST api/rnd/ncp-records/{ncpRecord}/intervention/recommend' => [
            'classification' => 'intentionally_not_audited',
            'source' => 'App\\Http\\Controllers\\RND\\MealPlanController@recommend',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Unsaved AI output must not persist prompts or outputs.',
        ],
        'POST api/rnd/ncp-records/{ncpRecord}/meal-plans' => [
            'classification' => 'model_event',
            'source' => 'App\\Models\\MealPlan::AuditsChanges',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'Meal-plan persistence for POST api/rnd/ncp-records/{ncpRecord}/meal-plans is covered by its redacted clinical model event.',
        ],
        'POST api/rnd/ncp-records/{ncpRecord}/meal-plans/from-template' => [
            'classification' => 'model_event',
            'source' => 'App\\Models\\MealPlan::AuditsChanges',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'Meal-plan persistence for POST api/rnd/ncp-records/{ncpRecord}/meal-plans/from-template is covered by its redacted clinical model event.',
        ],
        'POST api/rnd/ncp-records/{ncpRecord}/meal-plans/generate' => [
            'classification' => 'model_event',
            'source' => 'App\\Models\\MealPlan::AuditsChanges',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'Meal-plan persistence for POST api/rnd/ncp-records/{ncpRecord}/meal-plans/generate is covered by its redacted clinical model event.',
        ],
        'PATCH api/rnd/ncp-records/{ncpRecord}/meal-plans/{mealPlan}' => [
            'classification' => 'model_event',
            'source' => 'App\\Models\\MealPlan::AuditsChanges',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'Meal-plan persistence for PATCH api/rnd/ncp-records/{ncpRecord}/meal-plans/{mealPlan} is covered by its redacted clinical model event.',
        ],
        'DELETE api/rnd/ncp-records/{ncpRecord}/meal-plans/{mealPlan}' => [
            'classification' => 'model_event',
            'source' => 'App\\Models\\MealPlan::AuditsChanges',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'Meal-plan persistence for DELETE api/rnd/ncp-records/{ncpRecord}/meal-plans/{mealPlan} is covered by its redacted clinical model event.',
        ],
        'POST api/rnd/ncp-records/{ncpRecord}/meal-plans/{mealPlan}/days/{day}/items' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\RND\\MealPlanItemController@store',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'This meal-plan child command needs an explicit NCP-root event; clinical values remain excluded.',
        ],
        'PATCH api/rnd/ncp-records/{ncpRecord}/meal-plans/{mealPlan}/days/{day}/items/{item}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\RND\\MealPlanItemController@update',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'This meal-plan child command needs an explicit NCP-root event; clinical values remain excluded.',
        ],
        'DELETE api/rnd/ncp-records/{ncpRecord}/meal-plans/{mealPlan}/days/{day}/items/{item}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\RND\\MealPlanItemController@destroy',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'This meal-plan child command needs an explicit NCP-root event; clinical values remain excluded.',
        ],
        'POST api/rnd/ncp-records/{ncpRecord}/meal-plans/{mealPlan}/save-template' => [
            'classification' => 'model_event',
            'source' => 'App\\Models\\MealPlan::AuditsChanges',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'Meal-plan persistence for POST api/rnd/ncp-records/{ncpRecord}/meal-plans/{mealPlan}/save-template is covered by its redacted clinical model event.',
        ],
        'POST api/rnd/ncp-records/{ncpRecord}/monitorings' => [
            'classification' => 'model_event',
            'source' => 'App\\Models\\Monitoring::AuditsChanges',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'Monitoring persistence for POST api/rnd/ncp-records/{ncpRecord}/monitorings is covered by its redacted clinical model event.',
        ],
        'POST api/rnd/ncp-records/{ncpRecord}/monitorings/ai-review' => [
            'classification' => 'intentionally_not_audited',
            'source' => 'App\\Http\\Controllers\\RND\\MonitoringController@aiReview',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Unsaved AI review output must not persist prompts or outputs.',
        ],
        'PATCH api/rnd/ncp-records/{ncpRecord}/monitorings/{monitoring}' => [
            'classification' => 'model_event',
            'source' => 'App\\Models\\Monitoring::AuditsChanges',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'Monitoring persistence for PATCH api/rnd/ncp-records/{ncpRecord}/monitorings/{monitoring} is covered by its redacted clinical model event.',
        ],
        'DELETE api/rnd/ncp-records/{ncpRecord}/monitorings/{monitoring}' => [
            'classification' => 'model_event',
            'source' => 'App\\Models\\Monitoring::AuditsChanges',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'Monitoring persistence for DELETE api/rnd/ncp-records/{ncpRecord}/monitorings/{monitoring} is covered by its redacted clinical model event.',
        ],
        'POST api/rnd/patients' => [
            'classification' => 'model_event',
            'source' => 'App\\Models\\Patient::AuditsChanges',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'Patient persistence for POST api/rnd/patients is covered by its redacted clinical model event.',
        ],
        'PUT|PATCH api/rnd/patients/{patient}' => [
            'classification' => 'model_event',
            'source' => 'App\\Models\\Patient::AuditsChanges',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'Patient persistence for PUT|PATCH api/rnd/patients/{patient} is covered by its redacted clinical model event.',
        ],
        'DELETE api/rnd/patients/{patient}' => [
            'classification' => 'model_event',
            'source' => 'App\\Models\\Patient::AuditsChanges',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'Patient persistence for DELETE api/rnd/patients/{patient} is covered by its redacted clinical model event.',
        ],
        'POST api/rnd/patients/{patient}/ncp-records' => [
            'classification' => 'model_event',
            'source' => 'App\\Models\\NcpRecord::AuditsChanges',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'NCP record persistence for POST api/rnd/patients/{patient}/ncp-records is covered by its redacted clinical model event.',
        ],
        'POST api/rnd/recipes' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\RND\\RecipeController@store',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful POST api/rnd/recipes emits one sanitized explicit event; rejected commands emit none.',
        ],
        'PUT|PATCH api/rnd/recipes/{recipe}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\RND\\RecipeController@update',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful PUT|PATCH api/rnd/recipes/{recipe} emits one sanitized explicit event; rejected commands emit none.',
        ],
        'DELETE api/rnd/recipes/{recipe}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\RND\\RecipeController@destroy',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful DELETE api/rnd/recipes/{recipe} emits one sanitized explicit event; rejected commands emit none.',
        ],
        'POST api/rnd/report-branding' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\ReportBrandingController@update',
            'owner_task' => 8,
            'implementation_state' => 'planned',
            'reason' => 'This report-configuration command needs an explicit safe allow-listed change event; images and arbitrary payloads stay excluded.',
        ],
        'PATCH api/rnd/report-templates/{reportTemplate}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\ReportTemplateController@update',
            'owner_task' => 8,
            'implementation_state' => 'planned',
            'reason' => 'This report-configuration command needs an explicit safe allow-listed change event; images and arbitrary payloads stay excluded.',
        ],
        'POST api/rnd/reports' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\ReportController@store',
            'owner_task' => 8,
            'implementation_state' => 'planned',
            'reason' => 'This report lifecycle command needs an explicit outcome event without report snapshots, filters, or file contents.',
        ],
        'POST api/rnd/reports/generate-all' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\ReportController@generateAll',
            'owner_task' => 8,
            'implementation_state' => 'planned',
            'reason' => 'This report lifecycle command needs an explicit outcome event without report snapshots, filters, or file contents.',
        ],
        'DELETE api/rnd/reports/{report}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\ReportController@destroy',
            'owner_task' => 8,
            'implementation_state' => 'planned',
            'reason' => 'This report lifecycle command needs an explicit outcome event without report snapshots, filters, or file contents.',
        ],
        'POST api/rnd/reports/{type}/archive' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\ReportController@archive',
            'owner_task' => 8,
            'implementation_state' => 'planned',
            'reason' => 'This report lifecycle command needs an explicit outcome event without report snapshots, filters, or file contents.',
        ],
        'DELETE api/rnd/screening-documents/{screeningDocument}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\RND\\ScreeningDocumentController@destroy',
            'owner_task' => 6,
            'implementation_state' => 'planned',
            'reason' => 'This sensitive attachment command needs an explicit root-context event without paths, file contents, or OCR data.',
        ],
        'POST api/rnd/usda/import/{fdcId}' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\RND\\UsdaController@import',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful POST api/rnd/usda/import/{fdcId} emits one sanitized explicit event; rejected commands emit none.',
        ],
        'POST api/sop' => [
            'classification' => 'explicit_event',
            'source' => 'App\\Http\\Controllers\\SopController@store',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Successful POST api/sop emits one sanitized explicit event; rejected commands emit none.',
        ],
        'PUT storage/{path}' => [
            'classification' => 'intentionally_not_audited',
            'source' => 'Illuminate\\Filesystem\\FilesystemServiceProvider@serveFiles',
            'owner_task' => 4,
            'implementation_state' => 'implemented',
            'reason' => 'Laravel local-storage serving is framework infrastructure, not an application command.',
        ],
    ],
];
