version: '3.8'

services:
  mysql:
    image: 'mysql:8.0'
    container_name: 'nutriscope_mysql'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'nutriscope'
    volumes:
      - 'nutriscope_mysql:/var/lib/mysql'
    networks:
      - nutriscope_net
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: 'redis:alpine'
    container_name: 'nutriscope_redis'
    ports:
      - '6379:6379'
    volumes:
      - 'nutriscope_redis:/data'
    networks:
      - nutriscope_net
    restart: unless-stopped

volumes:
  nutriscope_mysql:
    driver: local
  nutriscope_redis:
    driver: local

networks:
  nutriscope_net:
    driver: bridge
